### ISSUE TITLE
404 Not Found using repo install script

### ISSUE THREAD

**Issue by archie** [treasure-data/elastic-beanstalk-td-agent#4]
Hi, 

Recently upgraded the to the latest AMI release on Elastic Beanstalk and the td-agent install script started failing. 

Running `curl -L https://td-toolbelt.herokuapp.com/sh/install-redhat-td-agent2.sh | sh` results in 

```sh
$ curl -L https://td-toolbelt.herokuapp.com/sh/install-redhat-td-agent2.sh | sh

This script requires superuser access to install rpm packages.
You will be prompted for your password by sudo.
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/2015.09
amzn-updates/2015.09
http://packages.treasuredata.com/2/redhat/2015.09/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
```

Version info from the elastic beanstalk machine

```sh
$ python -c 'import json,yum;yb=yum.YumBase();print(json.dumps(yb.conf.yumvar,indent=4))'
Loaded plugins: priorities, update-motd, upgrade-helper
{
    "uuid": "4ff215c1-1a3a-4443-a318-dcc77d809541",
    "basearch": "x86_64",
    "awsregion": "us-east-1",
    "releasever": "2015.09",
    "awsdomain": "amazonaws.com",
    "guid": "1ccace57c6e3",
    "arch": "ia32e"
}
```

Guessing that the version it's looking for is not available. From the .sh script downloaded version is populated automatically, is this really desired? 

What is the best way to correct this? 

Ps. Apologies if this is the wrong repo to submit this issue. Let me know where it should be if not here.

**Comment by markplindsay** [comment]
Hello treasure-data, I am having this problem too. 

It looks like the `redhat` directory on packages.treasuredata.com (specified within `install-redhat-td-agent2.sh`) is empty. This is not the case for the `ubuntu`, `debian`, etc. directories.

This is what I get when I visit http://packages.treasuredata.com/2/redhat/ in my browser:

```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: 2/redhat/index.html
RequestId: FDD9D124558D69ED
HostId: vW4j1aObz+R71MprqvlXZkob0MWF5t169FMjKeUiaa3bT/T0aJy/UtDEMuVoMPkhhezZv+MVY4E=
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html
```

Thanks a lot!!!

**Comment by repeatedly** [comment]
Yes. Amazon Linux uses original `$releaesver` value and it causes this problem.
We have a plan to provide new rpm for Amazon Linux 2015.09 in this month.
If rpm for Amazon Linux 2015.03 works on 2015.09, we can alias it.

**Comment by repeatedly** [comment]
> This is what I get when I visit http://packages.treasuredata.com/2/redhat/ in my browser:

This is another problem. Our repository is on S3 so need S3 browser.
http://packages.treasuredata.com/
https://td-agent-package-browser.herokuapp.com/2/redhat/

**Comment by repeatedly** [comment]
I will build td-agent 2 for 2015.09.
Please wait.

**Comment by archie** [comment]
Thanks Masahiro!

fwiw, 2015.03 works and I've tested it successfully with from Amazon's
2015.09 image.

2015-11-11 12:05 GMT+01:00 Masahiro Nakagawa <notifications@github.com>:

**Comment by repeatedly** [comment]
I just uploaded td-agent 2 rpm to 2015.09 path.
Could you test on your environment?

**Comment by archie** [comment]
@repeatedly Excellent! Will test tomorrow morning.

**Comment by markplindsay** [comment]
@repeatedly The install that failed yesterday just worked perfectly on my EB instance:

`2015-11-11 21:36:01 +0000 [info]: listening fluent socket on 0.0.0.0:24224`

Thank you very much for your quick response!

**Comment by repeatedly** [comment]
@markplindsay Good :)
Thanks for testing.

**Comment by archie** [comment]
Yes, it works here too. Going to close this issue.  

Thanks @repeatedly for updating the rpm repo.
