### ISSUE TITLE
Install script fails on amazon elastic beanstalk

### ISSUE THREAD

**Issue by knzwats** [treasure-data/elastic-beanstalk-td-agent#5]
Hi.

I tried to install td-agent on my elastic beanstalk environment with the install script, but encountered the 404 error below.

```
http://packages.treasuredata.com/2/redhat/2016.03/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
```

And I found this ticket [https://github.com/treasure-data/elastic-beanstalk-td-agent/issues/4], so I am guessing there is no build for releasever 2016.03 yet.
Would you be able to create a build for that version?

Best regards.

**Comment by repeatedly** [comment]
handle this it on https://github.com/treasure-data/omnibus-td-agent/issues/75.
